<script setup lang="ts">
import { site } from '~/site'

// The site is English, so the page reads the `en` side of every localised
// field. The `de` side exists for the PDF — see scripts/build-cv.ts.
const { data: cv } = await useAsyncData('cv', () => queryCollection('cv').first())

useSeo({
  title: 'CV',
  description: site.cv.description,
})

// A skill name is a plain string for the ones that are the same in both
// languages (Java, Vue) and a localised pair for the ones that are not. Both
// arrive here, so both have to be unwrapped — reading `.name` straight printed
// "[object Object]" on the page and in the Person schema below.
const skillName = (n: string | { en: string, de: string }) =>
  (typeof n === 'string' ? n : n.en)

// Built by `npm run cv` into public/cv/. Named after the person rather than
// the site, because the filename is what ends up in a recruiter's downloads.
const pdfs = [
  { label: 'CV (English)', href: '/cv/lukas-brackmann-cv.pdf' },
  { label: 'Lebenslauf (Deutsch)', href: '/cv/lukas-brackmann-lebenslauf.pdf' },
]

// Person schema is worth more here than anywhere else on the site: it is what
// lets a search engine connect the name to the role, employer and skills.
const schema = computed(() => cv.value && {
  '@context': 'https://schema.org',
  '@type': 'Person',
  'name': cv.value.name,
  'jobTitle': cv.value.headline.en,
  'email': `mailto:${cv.value.email}`,
  'address': { '@type': 'PostalAddress', 'addressLocality': 'Heidelberg', 'addressCountry': 'DE' },
  'worksFor': cv.value.experience?.[0] && {
    '@type': 'Organization',
    'name': cv.value.experience[0]!.org,
  },
  'knowsAbout': (cv.value.skills ?? []).flatMap(s => s.items.map(i => skillName(i.name))),
  'knowsLanguage': (cv.value.languages ?? []).map(l => l.name.en),
  'url': 'https://goatly.dev/cv',
})

useHead(() => ({
  script: schema.value
    ? [{ type: 'application/ld+json', innerHTML: JSON.stringify(schema.value) }]
    : [],
}))
</script>

<template>
  <div v-if="cv" class="cv-page mx-auto max-w-3xl">
    <!-- Identity, closed by the amber rule. Same device as the A4 template:
         the block that says who this is ends somewhere definite, so the facts
         under it read as a separate zone rather than as four more lines. -->
    <header>
      <div class="prompt-bar mb-4 w-10" />
      <h1 class="text-3xl font-bold tracking-tight sm:text-4xl">{{ cv.name }}</h1>
      <p class="mt-1.5 font-display text-lg text-accent">{{ cv.headline.en }}</p>
      <p class="mt-3 max-w-prose text-sm text-muted sm:text-base">{{ cv.tagline.en }}</p>

      <!-- The facts take the page's own gutter, so the header is built out of
           the same part as everything under it. They were a loose mono row, two
           buttons and an orphan sentence, each with its own left edge and its
           own idea of what size it was: four things stacked, rather than one
           block. The rule below the tagline is the section device as well —
           the full-width amber line it replaces was the only one of its kind
           on the page. -->
      <dl class="cv-sec cv-sec-tight space-y-3">
        <div class="cv-row">
          <dt class="cv-when">location</dt>
          <dd class="text-sm">{{ cv.location.en }}</dd>
        </div>

        <div class="cv-row">
          <dt class="cv-when">email</dt>
          <dd class="text-sm">
            <a
              :href="`mailto:${cv.email}`"
              class="text-accent transition hover:text-accent-hover"
            >{{ cv.email }}</a>
          </dd>
        </div>

        <div class="cv-row">
          <dt class="cv-when">links</dt>
          <dd class="flex flex-wrap gap-x-5 gap-y-1 text-sm">
            <!-- Amber like the email above it: on this page a link is amber,
                 and these were the only ones that were not. -->
            <a
              v-for="l in cv.links"
              :key="l.url"
              :href="l.url"
              class="text-accent transition hover:text-accent-hover"
            >{{ l.label }}</a>
          </dd>
        </div>

        <div class="cv-row">
          <dt class="cv-when">pdf</dt>
          <dd>
            <!-- Generated by `npm run cv` and committed. These are the public
                 pair — the --private pair carries the address and stays in
                 gitignored cv-out/. -->
            <div class="flex flex-wrap gap-3">
              <a
                v-for="pdf in pdfs"
                :key="pdf.href"
                :href="pdf.href"
                download
                class="rounded-lg border border-border px-4 py-2 font-mono text-sm text-text transition hover:border-accent hover:text-accent"
              >
                ↓ {{ pdf.label }}
              </a>
            </div>
          </dd>
        </div>
      </dl>
    </header>

    <section class="cv-sec">
      <h2 class="cv-h prompt-heading">experience</h2>
      <ol class="cv-list space-y-8">
        <li v-for="job in cv.experience" :key="`${job.org}-${job.start}`" class="cv-row">
          <p class="cv-when">{{ formatRange(job.start, job.end) }}</p>
          <div class="min-w-0">
            <h3 class="cv-title">{{ job.role.en }}</h3>
            <p class="mt-0.5 text-sm text-muted">
              {{ job.org }}<template v-if="job.location">, {{ job.location }}</template>
            </p>
            <ul v-if="job.bullets?.length" class="mt-3 space-y-1.5">
              <li
                v-for="(b, i) in job.bullets"
                :key="i"
                class="relative pl-5 text-sm leading-relaxed before:absolute before:left-0 before:text-accent before:content-['▸']"
              >
                {{ b.en }}
              </li>
            </ul>
            <!-- The A4 template's `Stack:` line rather than the pill chips this
                 started as. Six outlined pills per job was the loudest thing on
                 the page, for information that is a footnote to the bullets —
                 and they were never links, so the pill shape promised an
                 affordance that was not there. -->
            <p v-if="job.stack?.length" class="cv-meta mt-3">
              <span class="text-accent">stack:</span> {{ job.stack.join(' · ') }}
            </p>
          </div>
        </li>
      </ol>
    </section>

    <section class="cv-sec">
      <h2 class="cv-h prompt-heading">education</h2>
      <ol class="cv-list space-y-8">
        <li v-for="e in cv.education" :key="`${e.title.en}-${e.start}`" class="cv-row">
          <p class="cv-when">{{ formatRange(e.start, e.end) }}</p>
          <div class="min-w-0">
            <h3 class="cv-title">
              {{ e.title.en }}
              <span v-if="e.grade" class="font-normal text-accent">· {{ e.grade }}</span>
            </h3>
            <p v-if="e.org" class="mt-0.5 text-sm text-muted">{{ e.org }}</p>
            <p v-if="e.note" class="mt-2 text-sm leading-relaxed text-muted">{{ e.note.en }}</p>
          </div>
        </li>
      </ol>
    </section>

    <section class="cv-sec">
      <h2 class="cv-h prompt-heading">internships</h2>
      <ol class="cv-list space-y-5">
        <li v-for="p in cv.internships" :key="`${p.org}-${p.start}`" class="cv-row">
          <p class="cv-when">{{ formatRange(p.start, p.end) }}</p>
          <div class="min-w-0">
            <!-- Body size, not entry size: these are minor entries and the
                 hierarchy should say so. -->
            <h3 class="cv-title text-sm">{{ p.title.en }}</h3>
            <p class="mt-0.5 text-sm text-muted">
              {{ p.org }}<template v-if="p.note"> — {{ p.note.en }}</template>
            </p>
          </div>
        </li>
      </ol>
    </section>

    <section class="cv-sec">
      <h2 class="cv-h prompt-heading">skills</h2>
      <dl class="space-y-6">
        <div v-for="s in cv.skills" :key="s.group.en" class="cv-row">
          <dt class="cv-when">{{ s.group.en }}</dt>
          <dd class="grid gap-x-10 gap-y-2 sm:grid-cols-2">
            <div
              v-for="i in s.items"
              :key="skillName(i.name)"
              class="flex items-baseline justify-between gap-3 text-sm"
            >
              <span>{{ skillName(i.name) }}</span>
              <span v-if="i.level" class="meter shrink-0" aria-hidden="true">
                <i v-for="n in 10" :key="n" :class="n <= Math.round(i.level / 10) ? 'on' : 'off'" />
              </span>
              <span v-if="i.level" class="sr-only">{{ i.level }} out of 100</span>
            </div>
          </dd>
        </div>
      </dl>
    </section>

    <!-- The A4 template's sidebar, folded into the page. These are short
         reference lists, not dated entries: they do not earn the date gutter,
         and a full-width band each left the bottom of the page stretched out
         over almost nothing. Three-up under one rule instead. -->
    <section class="cv-sec">
      <div class="grid gap-x-10 gap-y-9 sm:grid-cols-3">
        <div>
          <h2 class="cv-h cv-h-sub prompt-heading">languages</h2>
          <dl class="space-y-1.5 text-sm">
            <div v-for="l in cv.languages" :key="l.name.en" class="flex items-baseline gap-x-2">
              <dt class="font-medium">{{ l.name.en }}</dt>
              <dd class="text-muted">— {{ l.level.en }}</dd>
              <!-- Decorative: the level is already written out beside it, so a
                   screen reader gains nothing from a second telling. -->
              <span v-if="l.meter" class="meter ml-auto shrink-0" aria-hidden="true">
                <i v-for="n in 10" :key="n" :class="n <= Math.round(l.meter / 10) ? 'on' : 'off'" />
              </span>
            </div>
          </dl>
        </div>

        <div>
          <h2 class="cv-h cv-h-sub prompt-heading">certificates</h2>
          <ul class="space-y-2.5 text-sm">
            <li v-for="c in cv.certificates" :key="c.name.en">
              {{ c.name.en }}
              <span v-if="c.date" class="cv-meta mt-0.5 block">{{ formatMonthYear(c.date) }}</span>
            </li>
          </ul>
        </div>

        <div v-if="cv.interests?.length">
          <h2 class="cv-h cv-h-sub prompt-heading">interests</h2>
          <p class="text-sm text-muted">{{ cv.interests.map(i => i.en).join(' · ') }}</p>
        </div>
      </div>
    </section>
  </div>
</template>

<style scoped>
/* ---------------------------------------------------------------------------
   The same three rules that fixed the A4 template (scripts/cv-template.ts),
   applied to the page. They are here rather than in Tailwind classes because
   each is a fact about the whole document, and repeating it inline on seven
   sections is how it drifts.

   1. ONE GUTTER. Every section — experience, education, internships, skills,
      languages, certificates — puts its label in a fixed left column, so the
      page has a single vertical line the eye follows and every value starts at
      the same x. Previously only `internships` did this, which is why it was
      the one section that read cleanly.

   2. TYPE SCALE, four steps, far enough apart to read as deliberate:
      title (30/36px) · heading and entry title (18/16px) · prose (14px) ·
      mono facts (12px). It was six steps, two of them 2px apart, which the eye
      reads as noise rather than as hierarchy.

   3. FONT DISCIPLINE. Mono is a machine-generated fact: dates, section
      headings, tech stacks. Sans is prose, including the entry titles — those
      were mono, one size off a mono heading directly above them, so heading
      and entry looked like the same kind of thing.
--------------------------------------------------------------------------- */

/* On the page wrapper, not :root — a scoped style compiles to
   `:root[data-v-…]`, which matches nothing, and the grid then silently
   collapses to a single column because its template-columns is invalid. */
.cv-page {
  --cv-gutter: 10rem;
  --cv-gap: 1.5rem;
}

/* Spacing rhythm: inside an entry ~0.25rem, between entries 2rem, between
   sections 4rem. Each gap is roughly 4x and 2x the one below it, so the space
   itself says where a block ends — 3.5rem sections against 2rem entries was
   too near the same number to say anything. The rule is what makes the
   boundary explicit rather than merely wide. */
.cv-sec {
  position: relative;
  margin-top: 4rem;
  border-top: 1px solid var(--border);
  padding-top: 2rem;
}

/* The site's prompt-bar, sitting on the section rule rather than floating above
   the heading as it does on the home page. Same signature, one element fewer,
   and it gives the run of sections a colour rhythm the hairlines alone did
   not have. */
.cv-sec::before {
  content: "";
  position: absolute;
  top: -1px;
  left: 0;
  width: 2.5rem;
  height: 2px;
  border-radius: 2px;
  background-color: var(--accent);
}

/* A CV is a timeline, so the dated sections say so: one continuous rail down
   the column boundary the gutter already establishes, with a node per entry.
   Only the dated sections get it — skills and languages use the same gutter,
   but they are not a chronology and a rail would claim they were.

   Both the rail and the nodes are absolutely positioned, which is also what
   keeps them out of the grid: a static pseudo-element on .cv-row would become
   a third grid item and shove the content column sideways. */
@media (min-width: 640px) {
  .cv-list {
    position: relative;
  }

  .cv-list::before {
    content: "";
    position: absolute;
    top: 0.5rem;
    bottom: 0.5rem;
    left: calc(var(--cv-gutter) + var(--cv-gap) / 2);
    width: 1px;
    background-color: var(--border);
  }

  .cv-list > li {
    position: relative;
  }

  .cv-list > li::before {
    content: "";
    position: absolute;
    top: 0.45rem;
    left: calc(var(--cv-gutter) + var(--cv-gap) / 2 - 2.5px);
    width: 6px;
    height: 6px;
    border-radius: 1px;
    background-color: var(--accent);
  }
}

/* The header's own divider: the section device, at the shorter interval that
   says "still the same block" rather than "a new one". */
.cv-sec-tight {
  margin-top: 2.25rem;
  padding-top: 1.75rem;
}

.cv-h {
  margin-bottom: 1.5rem;
  font-family: var(--font-display);
  font-size: 1.125rem;
  font-weight: 700;
}

/* A heading inside the reference band: same voice, less air, because it
   introduces four lines rather than a whole section. */
.cv-h-sub {
  margin-bottom: 1rem;
  font-size: 1rem;
}

.cv-row {
  display: grid;
  gap: 0.25rem var(--cv-gap);
}

/* The gutter opens at sm. Narrower than that there is no room for two columns,
   so the label stacks above its value the way it always did. */
@media (min-width: 640px) {
  .cv-row {
    grid-template-columns: var(--cv-gutter) minmax(0, 1fr);
  }
}

/* 13px, not 12: at 12 the gutter and the stack lines were legible in the
   sense that the letters resolved, and tiring in the sense that nobody read
   them. 10rem is then what the widest range ("Sep 2021 – Sep 2024") needs
   without wrapping, which is what keeps the content column's left edge fixed. */
.cv-when {
  font-family: var(--font-mono);
  font-size: 0.8125rem;
  line-height: 1.5;
  color: var(--muted);
}

@media (min-width: 640px) {
  .cv-when {
    padding-top: 0.2rem; /* optical: sits on the title's baseline, not its box */
  }
}

/* Sans, against the mono section heading above it. */
.cv-title {
  font-family: var(--font-sans);
  font-size: 1rem;
  font-weight: 600;
  line-height: 1.4;
  letter-spacing: normal; /* the global heading rule tightens h3; prose does not want it */
}

.cv-meta {
  font-family: var(--font-mono);
  font-size: 0.8125rem;
  line-height: 1.6;
  color: var(--muted);
}

/* The A4 template's skill meter, same construction and same reason: ten
   discrete cells drawn as elements, never the block characters █/░ — the
   webfont ships no U+2588, so a fallback face supplies it at a different
   advance width and the cells come out gapped and ragged. */
.meter {
  display: flex;
  gap: 2px;
  align-self: center;
}
.meter i {
  width: 6px;
  height: 6px;
  border-radius: 1px;
  background-color: var(--border);
}
.meter .on {
  background-color: var(--accent);
}
</style>
